[project]
name = "greencycle"
version = "0.1.0"
requires-python = ">=3.9,<3.12"
dependencies = [
    "tensorflow-cpu==2.12.0",
    "numpy<1.24",
    "Pillow",
    "opencv-python-headless",
    "fastapi",
    "uvicorn",
    "python-multipart",
    "h5py"
]
